name: test  # required to use null safety
description: Una simple aplicación de consola para obtener la cotización del dólar respecto al peso argentino.

environment:
  sdk: '>=2.10.0 <3.0.0'  # required to use null safety

dependencies:
  http: ^0.12.2
  html: ^0.14.0+4

dev_dependencies:
  pedantic: ^1.9.0